# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

# 이름 지정
name: Python Scrapper

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Scrapper
      run: |
        python "scrapping.py"
    - name: Commits
      run: |
        git config --local user.email "wonhyeok.contact@gmail.com"
        git config --local user.name "WonhyeokJUng"
        git add news.json
        git commit -m "[feat]Auto Update File" 
    - name: Test with pytest
      run: |
        pytest
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'master'
        github_token: $ 
